/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as BackRouteImport } from './routes/back'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as StoryRouteImport } from './routes/story'
import { Route as Top10RouteImport } from './routes/top-10'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const BackRoute = BackRouteImport.update({
  id: '/back',
  path: '/back',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const Top10Route = Top10RouteImport.update({
  id: '/top-10',
  path: '/top-10',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/back': typeof BackRoute
  '/contents': typeof ContentsRoute
  '/interview': typeof InterviewRoute
  '/letter': typeof LetterRoute
  '/photos': typeof PhotosRoute
  '/quiz': typeof QuizRoute
  '/story': typeof StoryRoute
  '/top-10': typeof Top10Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/back': typeof BackRoute
  '/contents': typeof ContentsRoute
  '/interview': typeof InterviewRoute
  '/letter': typeof LetterRoute
  '/photos': typeof PhotosRoute
  '/quiz': typeof QuizRoute
  '/story': typeof StoryRoute
  '/top-10': typeof Top10Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/back': typeof BackRoute
  '/contents': typeof ContentsRoute
  '/interview': typeof InterviewRoute
  '/letter': typeof LetterRoute
  '/photos': typeof PhotosRoute
  '/quiz': typeof QuizRoute
  '/story': typeof StoryRoute
  '/top-10': typeof Top10Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/back'
    | '/contents'
    | '/interview'
    | '/letter'
    | '/photos'
    | '/quiz'
    | '/story'
    | '/top-10'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/back'
    | '/contents'
    | '/interview'
    | '/letter'
    | '/photos'
    | '/quiz'
    | '/story'
    | '/top-10'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/back'
    | '/contents'
    | '/interview'
    | '/letter'
    | '/photos'
    | '/quiz'
    | '/story'
    | '/top-10'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  BackRoute: typeof BackRoute
  ContentsRoute: typeof ContentsRoute
  InterviewRoute: typeof InterviewRoute
  LetterRoute: typeof LetterRoute
  PhotosRoute: typeof PhotosRoute
  QuizRoute: typeof QuizRoute
  StoryRoute: typeof StoryRoute
  Top10Route: typeof Top10Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back': {
      id: '/back'
      path: '/back'
      fullPath: '/back'
      preLoaderRoute: typeof BackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-10': {
      id: '/top-10'
      path: '/top-10'
      fullPath: '/top-10'
      preLoaderRoute: typeof Top10RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  BackRoute: BackRoute,
  ContentsRoute: ContentsRoute,
  InterviewRoute: InterviewRoute,
  LetterRoute: LetterRoute,
  PhotosRoute: PhotosRoute,
  QuizRoute: QuizRoute,
  StoryRoute: StoryRoute,
  Top10Route: Top10Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
